# Train SVM classifier using sklearn digits dataset (i.e. from sklearn.datasets import load_digits) and then,

1.Measure accuracy of your model using different kernels such as rbf and linear.

2.Tune your model further using regularization and gamma parameters and try to come up with highest accurancy score

3.Use 80% of samples as training data size

In [24]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn

In [25]:
from sklearn.datasets import load_digits
digits = load_digits()

In [26]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [27]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [28]:
digits.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
digits.data.shape

(1797, 64)

In [30]:
digits.target.shape

(1797,)

In [31]:
df = pd.DataFrame(digits.data, digits.target)
df.head()

0    1    2     3     4     5    6    7    8    9   ...   54   55   56  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  5.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  9.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

    57   58    59    60    61   62   63  
0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4  0.0  0.0   2.0  16.0   4.0  0.0  0.0  

[5 rows x 64 columns]

In [32]:
df['target'] = digits.target
df.head(10)

0    1     2     3     4     5     6    7    8    9  ...   55   56   57  \
0  0.0  0.0   5.0  13.0   9.0   1.0   0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1  0.0  0.0   0.0  12.0  13.0   5.0   0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2  0.0  0.0   0.0   4.0  15.0  12.0   0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3  0.0  0.0   7.0  15.0  13.0   1.0   0.0  0.0  0.0  8.0  ...  0.0  0.0  0.0   
4  0.0  0.0   0.0   1.0  11.0   0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
5  0.0  0.0  12.0  10.0   0.0   0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
6  0.0  0.0   0.0  12.0  13.0   0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
7  0.0  0.0   7.0   8.0  13.0  16.0  15.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   
8  0.0  0.0   9.0  14.0   8.0   1.0   0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
9  0.0  0.0  11.0  12.0   0.0   0.0   0.0  0.0  0.0  2.0  ...  0.0  0.0  0.0   

     58    59    60    61   62   63  target  
0   6.0  13.0  10.0   0.0  0.0  0.0       0  
1   0.0  11.0  16.0  10.0  0.0  0.0       1  
2   0.0   3.0  11.0  16.0  9.0  0.0       2  
3   7.0  13.0  13.0   9.0  0.0  0.0       3  
4   0.0   2.0  16.0   4.0  0.0  0.0       4  
5   9.0  16.0  16.0  10.0  0.0  0.0       5  
6   1.0   9.0  15.0  11.0  3.0  0.0       6  
7  13.0   5.0   0.0   0.0  0.0  0.0       7  
8  11.0  16.0  15.0  11.0  1.0  0.0       8  
9   9.0  12.0  13.0   3.0  0.0  0.0       9  

[10 rows x 65 columns]

In [33]:
df.corr()

0         1         2         3         4         5         6  \
0      NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1      NaN  1.000000  0.556618  0.207814 -0.018761  0.060776  0.048388   
2      NaN  0.556618  1.000000  0.560180 -0.084235  0.043569  0.002841   
3      NaN  0.207814  0.560180  1.000000  0.023938 -0.171377 -0.115732   
4      NaN -0.018761 -0.084235  0.023938  1.000000  0.507731  0.127764   
...     ..       ...       ...       ...       ...       ...       ...   
60     NaN -0.102349 -0.134754 -0.065957 -0.082125 -0.351146 -0.383522   
61     NaN -0.029870 -0.041183 -0.054936 -0.215809 -0.268818 -0.304111   
62     NaN  0.026547  0.072599  0.053437 -0.250699 -0.267659 -0.178945   
63     NaN -0.043889  0.082523  0.081971 -0.215349 -0.167727 -0.080309   
target NaN -0.051834 -0.011836 -0.011489  0.100801  0.193362  0.197343   

               7         8         9  ...        55        56        57  \
0            NaN       NaN       NaN  ...       NaN       NaN       NaN   
1      -0.038927  0.032320  0.556372  ... -0.045342 -0.007905  0.855610   
2      -0.062278  0.022311  0.582259  ... -0.003804 -0.025837  0.515276   
3      -0.040139  0.035663  0.328344  ...  0.075335 -0.049085  0.175804   
4       0.010065  0.042065  0.051657  ... -0.212220  0.017352 -0.047223   
...          ...       ...       ...  ...       ...       ...       ...   
60     -0.178243  0.048996 -0.000604  ...  0.105101  0.005697 -0.117908   
61     -0.141174  0.033409  0.071488  ...  0.262795 -0.003056 -0.043889   
62     -0.063220  0.020689  0.111569  ...  0.511726 -0.011932  0.014557   
63     -0.024505 -0.005226 -0.001404  ...  0.563989 -0.004625 -0.047089   
target  0.101085  0.020813 -0.012439  ... -0.099312 -0.020518 -0.053950   

              58        59        60        61        62        63    target  
0            NaN       NaN       NaN       NaN       NaN       NaN       NaN  
1       0.555727  0.147646 -0.102349 -0.029870  0.026547 -0.043889 -0.051834  
2       0.937623  0.499840 -0.134754 -0.041183  0.072599  0.082523 -0.011836  
3       0.560326  0.767945 -0.065957 -0.054936  0.053437  0.081971 -0.011489  
4      -0.020176 -0.008867 -0.082125 -0.215809 -0.250699 -0.215349  0.100801  
...          ...       ...       ...       ...       ...       ...       ...  
60     -0.207957  0.058390  1.000000  0.609515  0.243305  0.103015 -0.196083  
61     -0.091839 -0.094956  0.609515  1.000000  0.648328  0.261991 -0.079100  
62      0.035369  0.006849  0.243305  0.648328  1.000000  0.620428 -0.114007  
63      0.031193  0.099671  0.103015  0.261991  0.620428  1.000000 -0.181929  
target  0.006367 -0.019790 -0.196083 -0.079100 -0.114007 -0.181929  1.000000  

[65 rows x 65 columns]

In [34]:
df.describe()

0            1            2            3            4  \
count  1797.0  1797.000000  1797.000000  1797.000000  1797.000000   
mean      0.0     0.303840     5.204786    11.835838    11.848080   
std       0.0     0.907192     4.754826     4.248842     4.287388   
min       0.0     0.000000     0.000000     0.000000     0.000000   
25%       0.0     0.000000     1.000000    10.000000    10.000000   
50%       0.0     0.000000     4.000000    13.000000    13.000000   
75%       0.0     0.000000     9.000000    15.000000    15.000000   
max       0.0     8.000000    16.000000    16.000000    16.000000   

                 5            6            7            8            9  ...  \
count  1797.000000  1797.000000  1797.000000  1797.000000  1797.000000  ...   
mean      5.781859     1.362270     0.129661     0.005565     1.993879  ...   
std       5.666418     3.325775     1.037383     0.094222     3.196160  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       4.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%      11.000000     0.000000     0.000000     0.000000     3.000000  ...   
max      16.000000    16.000000    15.000000     2.000000    16.000000  ...   

                55           56           57           58           59  \
count  1797.000000  1797.000000  1797.000000  1797.000000  1797.000000   
mean      0.206455     0.000556     0.279354     5.557596    12.089037   
std       0.984401     0.023590     0.934302     5.103019     4.374694   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     1.000000    11.000000   
50%       0.000000     0.000000     0.000000     4.000000    13.000000   
75%       0.000000     0.000000     0.000000    10.000000    16.000000   
max      13.000000     1.000000     9.000000    16.000000    16.000000   

                60           61           62           63       target  
count  1797.000000  1797.000000  1797.000000  1797.000000  1797.000000  
mean     11.809126     6.764051     2.067891     0.364496     4.490818  
std       4.933947     5.900623     4.090548     1.860122     2.865304  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%      10.000000     0.000000     0.000000     0.000000     2.000000  
50%      14.000000     6.000000     0.000000     0.000000     4.000000  
75%      16.000000    12.000000     2.000000     0.000000     7.000000  
max      16.000000    16.000000    16.000000    16.000000     9.000000  

[8 rows x 65 columns]

# Visualization

In [35]:
fig = plt.figure(figsize=(10,12))
fig.subplots_adjust(left=0, right=1, bottom=0, top=1, hspace=0.05, wspace=0.05)
for i in range(64):
  ax = fig.add_subplot(8,8, i+1, xticks=[], yticks=[])
  ax.imshow(digits.images[i], cmap=plt.cm.binary, interpolation='nearest')
  ax.text(0, 7, str(digits.target[i]))

In [37]:
sns.set(rc={'figure.figsize':(30,30)})
correlation_matrix = df.corr().round(1)
sns.heatmap(data=correlation_matrix, annot=True)

<AxesSubplot:>

# Splitting the Data into Dependent and Indpendent variables

In [38]:
x = df.drop('target',axis='columns')
y = df.target


# Training and Testing the Data

In [39]:
from sklearn.model_selection import train_test_split

In [43]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=5)

# Support Vector Machine

In [44]:
from sklearn.svm import SVC

In [45]:
model = SVC()

In [46]:
model.fit(xtrain, ytrain)

SVC()

# Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix
cm = np.array(confusion_matrix(ytest, ypred))
cm

array([[35,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 35,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 36,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 35,  0,  1,  0,  0,  1,  0],
       [ 0,  0,  0,  0, 32,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 45,  0,  0,  0,  1],
       [ 0,  0,  0,  0,  0,  0, 30,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 41,  0,  1],
       [ 0,  1,  0,  0,  0,  0,  0,  0, 36,  1],
       [ 0,  0,  0,  0,  0,  1,  0,  0,  1, 27]])

In [ ]:
sns.set(rc={'figure.figsize':(8,6)})
sns.heatmap(pd.DataFrame(cm), annot=True, cmap="RdYlBu_r" ,fmt='g')
ax.xaxis.set_label_position("top")
plt.tight_layout()
plt.title('Confusion matrix', y=5.1)
plt.ylabel('Actual label')
plt.xlabel('Predicted label')

Text(0.5, 30.5, 'Predicted label')

# Accuracy

In [ ]:
from sklearn.metrics import accuracy_score
ac = accuracy_score(ytest, ypred)
ac

0.9777777777777777

In [ ]:
model.score(xtest, ytest)

0.9777777777777777

In [ ]:
model_c = SVC(C=10)
model_c.fit(xtrain, ytrain)
model_c.score(xtest, ytest)

0.9861111111111112

# Kernel

In [ ]:
model_linear = SVC(kernel='linear', C=0.005,probability=True )
model_linear.fit(xtrain, ytrain)
model_linear.score(xtest, ytest)

0.9777777777777777

In [ ]:
model_rbf = SVC(kernel='rbf', gamma=0.002,probability=True)
model_rbf.fit(xtrain, ytrain)
model_rbf.score(xtest, ytest)

0.9805555555555555