# Assignment/Task 4

## GO_STP_2

#### Task Link : https://www.goeduhub.com/11546/question-exercise-practice-solutions-science-machine-learning

#### 1. Import the numpy package under the name np and Print the numpy version and the configuration 

In [1]:
import numpy as np
print("Version: {}".format(np.__version__))
print(np.show_config())

Version: 1.19.3
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


#### 2. Create a null vector of size 10


In [2]:
x= np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
a= np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [4]:
a.dtype

dtype('int32')

In [5]:
type(a)

numpy.ndarray

#### 3. Create Simple 1-D array and check type and check data types in array.

In [6]:
import numpy as np
a = np.array([5,10,15,20])
print(a)
print(type(a))
print(a.dtype)

[ 5 10 15 20]
<class 'numpy.ndarray'>
int32


#### 4.How to find number of dimensions, bytes per element and bytes of memory used?

In [7]:
import sys
a = np.arange(1,10).reshape(3,3)
print(f"dimension: {a.shape}")
print("Bytes per Element: {}".format(a.itemsize))
print("Memory size of numpy array is " +str(a.size*a.itemsize))

dimension: (3, 3)
Bytes per Element: 4
Memory size of numpy array is 36


#### 5. Create a null vector of size 10 but the fifth value which is 1

In [9]:
a = (np.arange(10)==4).astype(int)
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

 #### 6. Create a vector with values ranging from 10 to 49

In [11]:
a=np.arange(10,50)
print(a)
# Reverse a vector (first element becomes last)
print("\n Reversed vector\n",np.flipud(a))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

 Reversed vector
 [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 7. Reverse a vector (first element becomes last)

In [12]:
import numpy as np
a = np.array([10,20,30,40,24,17,4,8,13,12])
print(a[::-1])

[12 13  8  4 17 24 40 30 20 10]


#### 8.Create a 3x3 matrix with values ranging from 0 to 8

In [13]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 9. Find indices of non-zero elements from [1,2,0,0,4,0]

In [14]:
a= np.array([1,2,0,0,4,0])
print("indexes of non-zero elements are:", np.nonzero(a))

indexes of non-zero elements are: (array([0, 1, 4], dtype=int64),)


#### 10. Create a 3x3 identity matrix

In [15]:
 np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Create a 3x3x3 array with random values

In [16]:
np.random.random((3,3,3))

array([[[0.87994985, 0.79395128, 0.20198935],
        [0.46133845, 0.70182381, 0.93448017],
        [0.02777151, 0.57187656, 0.54453229]],

       [[0.44833745, 0.86782489, 0.58071489],
        [0.85900196, 0.8726722 , 0.14758922],
        [0.80890179, 0.78948197, 0.96522579]],

       [[0.9302689 , 0.09963252, 0.31602571],
        [0.15771279, 0.6334174 , 0.09092248],
        [0.21458265, 0.8996219 , 0.09675419]]])

#### 12. Create a 10x10 array with random values and find the minimum and maximum values

In [17]:
a = np.random.random((10,10))
print('max value',a.max())
print('min value',a.min())
# Create a random vector of size 30 and find the mean value
vector = np.random.random(30)
print("Mean value is",vector.mean())
vector

max value 0.9971082695968364
min value 0.004979029081588648
Mean value is 0.481410598775416


array([0.08613378, 0.31172199, 0.63001921, 0.35770235, 0.38281383,
       0.74331789, 0.06469451, 0.08695693, 0.15345675, 0.59328952,
       0.12860082, 0.86943952, 0.87836383, 0.93218076, 0.96315058,
       0.21581501, 0.21522037, 0.81075913, 0.56619621, 0.10198195,
       0.72128398, 0.41611099, 0.64576915, 0.10018846, 0.04250096,
       0.2747528 , 0.66672302, 0.98198458, 0.91254714, 0.58864195])

#### 13. Create a random vector of size 30 and find the mean value.

In [20]:
import numpy as np
a = np.random.random(30)
print(a)
print("Mean value:",a.mean())

[0.37434525 0.00926207 0.62180977 0.92331225 0.86404005 0.93383409
 0.86000851 0.77216325 0.8065801  0.23921049 0.82598036 0.08680809
 0.94766909 0.24023371 0.17932632 0.41541743 0.84258973 0.13688958
 0.20909105 0.86931916 0.35909666 0.7743509  0.92986176 0.86867241
 0.39270686 0.25254148 0.97617952 0.34737718 0.04708921 0.04684128]
Mean value: 0.538420253916471


#### 14. Create a 2d array with 1 on the border and 0 inside.

In [22]:
a=np.ones((10,10))
print(a)
print(" \nArray with 1 on the border and 0 inside:")
a[1:-1, 1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
 
Array with 1 on the border and 0 inside:
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 15. How to add a border (filled with 0's) around an existing array? 

In [23]:
arr = np.arange(1,10).reshape(3,3)
np.pad(arr, pad_width=1, mode='constant', constant_values=0 )

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 0],
       [0, 4, 5, 6, 0],
       [0, 7, 8, 9, 0],
       [0, 0, 0, 0, 0]])

#### 16.How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?

Example -
[[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]

Get 13, get first row only, get 3rd column only, get [2, 4, 6], replace 13 by 20

In [24]:
import numpy as np
a = np.arange(1,15).reshape(2,7)
print(a)
print(a[1,5])
print(a[0,0:])
print(a[0:2,2])
print(a[0,1:6:2])
print(np.where(a==13, 20, a))

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
13
[1 2 3 4 5 6 7]
[ 3 10]
[2 4 6]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


#### 17. How to Convert a 1D array to a 2D array with 2 rows

In [25]:
import numpy as np
a = np.array([10,20,30,40,50,60]).reshape(2,3)
print(a)

[[10 20 30]
 [40 50 60]]


#### 18.Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:

a = np.array([1,2,3])`

Desired Output:

#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

#### 19.Write a program to show how Numpy taking less memory compared to Python List?

In [26]:
import numpy as np
l = range(1000)
import sys
a = 10
print(sys.getsizeof(a)) #memory allocated to a
print(sys.getsizeof(a)*len(l))
a1 = np.arange(1000)
print(a1.size)
print(a1.size*a1.itemsize)

28
28000
1000
4000


#### 20.Write a program to show how Numpy taking less time compared to Python List?

In [30]:
import numpy as np
import sys
import time

size = 1000000
l1 = range(size)
l2 = range(size)

start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]

n1 = np.arange(size)
n2 = np.arange(size)

#list itemwise sum
print((time.time()-start)*1000)

#numpy array itemwise sum
start = time.time()
result1 = n1+n2

print((time.time()-start)*1000)


109.23361778259277
0.0
